/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalysesRouteImport } from './routes/admin.analyses'
import { Route as AdminContractorsRouteImport } from './routes/admin.contractors'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ContractorIndexRouteImport } from './routes/contractor.index'
import { Route as ContractorHistoryRouteImport } from './routes/contractor.history'
import { Route as ContractorLoginRouteImport } from './routes/contractor.login'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TrackReferenceRouteImport } from './routes/track.$reference'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin.requests.index'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as ApiInternalMaintenanceRouteImport } from './routes/api.internal.maintenance'
import { Route as ApiV1ContractorsRouteImport } from './routes/api.v1.contractors'
import { Route as ContractorJobsIndexRouteImport } from './routes/contractor.jobs.index'
import { Route as ContractorJobsIdRouteImport } from './routes/contractor.jobs.$id'
import { Route as ApiInternalMlProcessRouteImport } from './routes/api.internal.ml.process'
import { Route as ApiV1AdminAnalysesRouteImport } from './routes/api.v1.admin.analyses'
import { Route as ApiV1AdminBootstrapRouteImport } from './routes/api.v1.admin.bootstrap'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api.v1.auth.login'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api.v1.auth.logout'
import { Route as ApiV1AuthMeRouteImport } from './routes/api.v1.auth.me'
import { Route as ApiV1ContractorBootstrapRouteImport } from './routes/api.v1.contractor.bootstrap'
import { Route as ApiV1PublicStatsRouteImport } from './routes/api.v1.public.stats'
import { Route as ApiV1RequestsIndexRouteImport } from './routes/api.v1.requests.index'
import { Route as ApiV1RequestsIdRouteImport } from './routes/api.v1.requests.$id'
import { Route as ApiV1PublicRequestsReferenceRouteImport } from './routes/api.v1.public.requests.$reference'
import { Route as ApiV1RequestsIdAssignRouteImport } from './routes/api.v1.requests.$id.assign'
import { Route as ApiV1RequestsIdNotesRouteImport } from './routes/api.v1.requests.$id.notes'
import { Route as ApiV1RequestsIdPhotoUploadsRouteImport } from './routes/api.v1.requests.$id.photo-uploads'
import { Route as ApiV1RequestsIdPhotosRouteImport } from './routes/api.v1.requests.$id.photos'
import { Route as ApiV1RequestsIdTransitionRouteImport } from './routes/api.v1.requests.$id.transition'
import { Route as ApiV1PhotosPhotoIdAnalysisRetryRouteImport } from './routes/api.v1.photos.$photoId.analysis.retry'
import { Route as ApiV1RequestsIdPhotoUploadsUploadIdCompleteRouteImport } from './routes/api.v1.requests.$id.photo-uploads.$uploadId.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalysesRoute = AdminAnalysesRouteImport.update({
  id: '/admin/analyses',
  path: '/admin/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractorsRoute = AdminContractorsRouteImport.update({
  id: '/admin/contractors',
  path: '/admin/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorIndexRoute = ContractorIndexRouteImport.update({
  id: '/contractor/',
  path: '/contractor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorHistoryRoute = ContractorHistoryRouteImport.update({
  id: '/contractor/history',
  path: '/contractor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorLoginRoute = ContractorLoginRouteImport.update({
  id: '/contractor/login',
  path: '/contractor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackReferenceRoute = TrackReferenceRouteImport.update({
  id: '/track/$reference',
  path: '/track/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/admin/requests/$id',
  path: '/admin/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMaintenanceRoute = ApiInternalMaintenanceRouteImport.update({
  id: '/api/internal/maintenance',
  path: '/api/internal/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContractorsRoute = ApiV1ContractorsRouteImport.update({
  id: '/api/v1/contractors',
  path: '/api/v1/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorJobsIndexRoute = ContractorJobsIndexRouteImport.update({
  id: '/contractor/jobs/',
  path: '/contractor/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorJobsIdRoute = ContractorJobsIdRouteImport.update({
  id: '/contractor/jobs/$id',
  path: '/contractor/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMlProcessRoute = ApiInternalMlProcessRouteImport.update({
  id: '/api/internal/ml/process',
  path: '/api/internal/ml/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminAnalysesRoute = ApiV1AdminAnalysesRouteImport.update({
  id: '/api/v1/admin/analyses',
  path: '/api/v1/admin/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminBootstrapRoute = ApiV1AdminBootstrapRouteImport.update({
  id: '/api/v1/admin/bootstrap',
  path: '/api/v1/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContractorBootstrapRoute =
  ApiV1ContractorBootstrapRouteImport.update({
    id: '/api/v1/contractor/bootstrap',
    path: '/api/v1/contractor/bootstrap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1PublicStatsRoute = ApiV1PublicStatsRouteImport.update({
  id: '/api/v1/public/stats',
  path: '/api/v1/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RequestsIndexRoute = ApiV1RequestsIndexRouteImport.update({
  id: '/api/v1/requests/',
  path: '/api/v1/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RequestsIdRoute = ApiV1RequestsIdRouteImport.update({
  id: '/api/v1/requests/$id',
  path: '/api/v1/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PublicRequestsReferenceRoute =
  ApiV1PublicRequestsReferenceRouteImport.update({
    id: '/api/v1/public/requests/$reference',
    path: '/api/v1/public/requests/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1RequestsIdAssignRoute = ApiV1RequestsIdAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => ApiV1RequestsIdRoute,
} as any)
const ApiV1RequestsIdNotesRoute = ApiV1RequestsIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiV1RequestsIdRoute,
} as any)
const ApiV1RequestsIdPhotoUploadsRoute =
  ApiV1RequestsIdPhotoUploadsRouteImport.update({
    id: '/photo-uploads',
    path: '/photo-uploads',
    getParentRoute: () => ApiV1RequestsIdRoute,
  } as any)
const ApiV1RequestsIdPhotosRoute = ApiV1RequestsIdPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => ApiV1RequestsIdRoute,
} as any)
const ApiV1RequestsIdTransitionRoute =
  ApiV1RequestsIdTransitionRouteImport.update({
    id: '/transition',
    path: '/transition',
    getParentRoute: () => ApiV1RequestsIdRoute,
  } as any)
const ApiV1PhotosPhotoIdAnalysisRetryRoute =
  ApiV1PhotosPhotoIdAnalysisRetryRouteImport.update({
    id: '/api/v1/photos/$photoId/analysis/retry',
    path: '/api/v1/photos/$photoId/analysis/retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute =
  ApiV1RequestsIdPhotoUploadsUploadIdCompleteRouteImport.update({
    id: '/$uploadId/complete',
    path: '/$uploadId/complete',
    getParentRoute: () => ApiV1RequestsIdPhotoUploadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/analyses': typeof AdminAnalysesRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/health': typeof ApiHealthRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/track/': typeof TrackIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/api/internal/maintenance': typeof ApiInternalMaintenanceRoute
  '/api/v1/contractors': typeof ApiV1ContractorsRoute
  '/contractor/jobs/$id': typeof ContractorJobsIdRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/contractor/jobs/': typeof ContractorJobsIndexRoute
  '/api/internal/ml/process': typeof ApiInternalMlProcessRoute
  '/api/v1/admin/analyses': typeof ApiV1AdminAnalysesRoute
  '/api/v1/admin/bootstrap': typeof ApiV1AdminBootstrapRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/contractor/bootstrap': typeof ApiV1ContractorBootstrapRoute
  '/api/v1/public/stats': typeof ApiV1PublicStatsRoute
  '/api/v1/requests/$id': typeof ApiV1RequestsIdRouteWithChildren
  '/api/v1/requests/': typeof ApiV1RequestsIndexRoute
  '/api/v1/public/requests/$reference': typeof ApiV1PublicRequestsReferenceRoute
  '/api/v1/requests/$id/assign': typeof ApiV1RequestsIdAssignRoute
  '/api/v1/requests/$id/notes': typeof ApiV1RequestsIdNotesRoute
  '/api/v1/requests/$id/photo-uploads': typeof ApiV1RequestsIdPhotoUploadsRouteWithChildren
  '/api/v1/requests/$id/photos': typeof ApiV1RequestsIdPhotosRoute
  '/api/v1/requests/$id/transition': typeof ApiV1RequestsIdTransitionRoute
  '/api/v1/photos/$photoId/analysis/retry': typeof ApiV1PhotosPhotoIdAnalysisRetryRoute
  '/api/v1/requests/$id/photo-uploads/$uploadId/complete': typeof ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/analyses': typeof AdminAnalysesRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/health': typeof ApiHealthRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/admin': typeof AdminIndexRoute
  '/contractor': typeof ContractorIndexRoute
  '/track': typeof TrackIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/api/internal/maintenance': typeof ApiInternalMaintenanceRoute
  '/api/v1/contractors': typeof ApiV1ContractorsRoute
  '/contractor/jobs/$id': typeof ContractorJobsIdRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/contractor/jobs': typeof ContractorJobsIndexRoute
  '/api/internal/ml/process': typeof ApiInternalMlProcessRoute
  '/api/v1/admin/analyses': typeof ApiV1AdminAnalysesRoute
  '/api/v1/admin/bootstrap': typeof ApiV1AdminBootstrapRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/contractor/bootstrap': typeof ApiV1ContractorBootstrapRoute
  '/api/v1/public/stats': typeof ApiV1PublicStatsRoute
  '/api/v1/requests/$id': typeof ApiV1RequestsIdRouteWithChildren
  '/api/v1/requests': typeof ApiV1RequestsIndexRoute
  '/api/v1/public/requests/$reference': typeof ApiV1PublicRequestsReferenceRoute
  '/api/v1/requests/$id/assign': typeof ApiV1RequestsIdAssignRoute
  '/api/v1/requests/$id/notes': typeof ApiV1RequestsIdNotesRoute
  '/api/v1/requests/$id/photo-uploads': typeof ApiV1RequestsIdPhotoUploadsRouteWithChildren
  '/api/v1/requests/$id/photos': typeof ApiV1RequestsIdPhotosRoute
  '/api/v1/requests/$id/transition': typeof ApiV1RequestsIdTransitionRoute
  '/api/v1/photos/$photoId/analysis/retry': typeof ApiV1PhotosPhotoIdAnalysisRetryRoute
  '/api/v1/requests/$id/photo-uploads/$uploadId/complete': typeof ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/analyses': typeof AdminAnalysesRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/health': typeof ApiHealthRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/track/': typeof TrackIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/api/internal/maintenance': typeof ApiInternalMaintenanceRoute
  '/api/v1/contractors': typeof ApiV1ContractorsRoute
  '/contractor/jobs/$id': typeof ContractorJobsIdRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/contractor/jobs/': typeof ContractorJobsIndexRoute
  '/api/internal/ml/process': typeof ApiInternalMlProcessRoute
  '/api/v1/admin/analyses': typeof ApiV1AdminAnalysesRoute
  '/api/v1/admin/bootstrap': typeof ApiV1AdminBootstrapRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/contractor/bootstrap': typeof ApiV1ContractorBootstrapRoute
  '/api/v1/public/stats': typeof ApiV1PublicStatsRoute
  '/api/v1/requests/$id': typeof ApiV1RequestsIdRouteWithChildren
  '/api/v1/requests/': typeof ApiV1RequestsIndexRoute
  '/api/v1/public/requests/$reference': typeof ApiV1PublicRequestsReferenceRoute
  '/api/v1/requests/$id/assign': typeof ApiV1RequestsIdAssignRoute
  '/api/v1/requests/$id/notes': typeof ApiV1RequestsIdNotesRoute
  '/api/v1/requests/$id/photo-uploads': typeof ApiV1RequestsIdPhotoUploadsRouteWithChildren
  '/api/v1/requests/$id/photos': typeof ApiV1RequestsIdPhotosRoute
  '/api/v1/requests/$id/transition': typeof ApiV1RequestsIdTransitionRoute
  '/api/v1/photos/$photoId/analysis/retry': typeof ApiV1PhotosPhotoIdAnalysisRetryRoute
  '/api/v1/requests/$id/photo-uploads/$uploadId/complete': typeof ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report'
    | '/admin/analyses'
    | '/admin/contractors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reports'
    | '/api/health'
    | '/contractor/history'
    | '/contractor/login'
    | '/track/$reference'
    | '/admin/'
    | '/contractor/'
    | '/track/'
    | '/admin/requests/$id'
    | '/api/internal/maintenance'
    | '/api/v1/contractors'
    | '/contractor/jobs/$id'
    | '/admin/requests/'
    | '/contractor/jobs/'
    | '/api/internal/ml/process'
    | '/api/v1/admin/analyses'
    | '/api/v1/admin/bootstrap'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/contractor/bootstrap'
    | '/api/v1/public/stats'
    | '/api/v1/requests/$id'
    | '/api/v1/requests/'
    | '/api/v1/public/requests/$reference'
    | '/api/v1/requests/$id/assign'
    | '/api/v1/requests/$id/notes'
    | '/api/v1/requests/$id/photo-uploads'
    | '/api/v1/requests/$id/photos'
    | '/api/v1/requests/$id/transition'
    | '/api/v1/photos/$photoId/analysis/retry'
    | '/api/v1/requests/$id/photo-uploads/$uploadId/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report'
    | '/admin/analyses'
    | '/admin/contractors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reports'
    | '/api/health'
    | '/contractor/history'
    | '/contractor/login'
    | '/track/$reference'
    | '/admin'
    | '/contractor'
    | '/track'
    | '/admin/requests/$id'
    | '/api/internal/maintenance'
    | '/api/v1/contractors'
    | '/contractor/jobs/$id'
    | '/admin/requests'
    | '/contractor/jobs'
    | '/api/internal/ml/process'
    | '/api/v1/admin/analyses'
    | '/api/v1/admin/bootstrap'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/contractor/bootstrap'
    | '/api/v1/public/stats'
    | '/api/v1/requests/$id'
    | '/api/v1/requests'
    | '/api/v1/public/requests/$reference'
    | '/api/v1/requests/$id/assign'
    | '/api/v1/requests/$id/notes'
    | '/api/v1/requests/$id/photo-uploads'
    | '/api/v1/requests/$id/photos'
    | '/api/v1/requests/$id/transition'
    | '/api/v1/photos/$photoId/analysis/retry'
    | '/api/v1/requests/$id/photo-uploads/$uploadId/complete'
  id:
    | '__root__'
    | '/'
    | '/report'
    | '/admin/analyses'
    | '/admin/contractors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reports'
    | '/api/health'
    | '/contractor/history'
    | '/contractor/login'
    | '/track/$reference'
    | '/admin/'
    | '/contractor/'
    | '/track/'
    | '/admin/requests/$id'
    | '/api/internal/maintenance'
    | '/api/v1/contractors'
    | '/contractor/jobs/$id'
    | '/admin/requests/'
    | '/contractor/jobs/'
    | '/api/internal/ml/process'
    | '/api/v1/admin/analyses'
    | '/api/v1/admin/bootstrap'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/contractor/bootstrap'
    | '/api/v1/public/stats'
    | '/api/v1/requests/$id'
    | '/api/v1/requests/'
    | '/api/v1/public/requests/$reference'
    | '/api/v1/requests/$id/assign'
    | '/api/v1/requests/$id/notes'
    | '/api/v1/requests/$id/photo-uploads'
    | '/api/v1/requests/$id/photos'
    | '/api/v1/requests/$id/transition'
    | '/api/v1/photos/$photoId/analysis/retry'
    | '/api/v1/requests/$id/photo-uploads/$uploadId/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportRoute: typeof ReportRoute
  AdminAnalysesRoute: typeof AdminAnalysesRoute
  AdminContractorsRoute: typeof AdminContractorsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ContractorHistoryRoute: typeof ContractorHistoryRoute
  ContractorLoginRoute: typeof ContractorLoginRoute
  TrackReferenceRoute: typeof TrackReferenceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContractorIndexRoute: typeof ContractorIndexRoute
  TrackIndexRoute: typeof TrackIndexRoute
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
  ApiInternalMaintenanceRoute: typeof ApiInternalMaintenanceRoute
  ApiV1ContractorsRoute: typeof ApiV1ContractorsRoute
  ContractorJobsIdRoute: typeof ContractorJobsIdRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  ContractorJobsIndexRoute: typeof ContractorJobsIndexRoute
  ApiInternalMlProcessRoute: typeof ApiInternalMlProcessRoute
  ApiV1AdminAnalysesRoute: typeof ApiV1AdminAnalysesRoute
  ApiV1AdminBootstrapRoute: typeof ApiV1AdminBootstrapRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1ContractorBootstrapRoute: typeof ApiV1ContractorBootstrapRoute
  ApiV1PublicStatsRoute: typeof ApiV1PublicStatsRoute
  ApiV1RequestsIdRoute: typeof ApiV1RequestsIdRouteWithChildren
  ApiV1RequestsIndexRoute: typeof ApiV1RequestsIndexRoute
  ApiV1PublicRequestsReferenceRoute: typeof ApiV1PublicRequestsReferenceRoute
  ApiV1PhotosPhotoIdAnalysisRetryRoute: typeof ApiV1PhotosPhotoIdAnalysisRetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analyses': {
      id: '/admin/analyses'
      path: '/admin/analyses'
      fullPath: '/admin/analyses'
      preLoaderRoute: typeof AdminAnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contractors': {
      id: '/admin/contractors'
      path: '/admin/contractors'
      fullPath: '/admin/contractors'
      preLoaderRoute: typeof AdminContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/': {
      id: '/contractor/'
      path: '/contractor'
      fullPath: '/contractor/'
      preLoaderRoute: typeof ContractorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/history': {
      id: '/contractor/history'
      path: '/contractor/history'
      fullPath: '/contractor/history'
      preLoaderRoute: typeof ContractorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/login': {
      id: '/contractor/login'
      path: '/contractor/login'
      fullPath: '/contractor/login'
      preLoaderRoute: typeof ContractorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$reference': {
      id: '/track/$reference'
      path: '/track/$reference'
      fullPath: '/track/$reference'
      preLoaderRoute: typeof TrackReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/admin/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/maintenance': {
      id: '/api/internal/maintenance'
      path: '/api/internal/maintenance'
      fullPath: '/api/internal/maintenance'
      preLoaderRoute: typeof ApiInternalMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contractors': {
      id: '/api/v1/contractors'
      path: '/api/v1/contractors'
      fullPath: '/api/v1/contractors'
      preLoaderRoute: typeof ApiV1ContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/jobs/': {
      id: '/contractor/jobs/'
      path: '/contractor/jobs'
      fullPath: '/contractor/jobs/'
      preLoaderRoute: typeof ContractorJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/jobs/$id': {
      id: '/contractor/jobs/$id'
      path: '/contractor/jobs/$id'
      fullPath: '/contractor/jobs/$id'
      preLoaderRoute: typeof ContractorJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/ml/process': {
      id: '/api/internal/ml/process'
      path: '/api/internal/ml/process'
      fullPath: '/api/internal/ml/process'
      preLoaderRoute: typeof ApiInternalMlProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/analyses': {
      id: '/api/v1/admin/analyses'
      path: '/api/v1/admin/analyses'
      fullPath: '/api/v1/admin/analyses'
      preLoaderRoute: typeof ApiV1AdminAnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/bootstrap': {
      id: '/api/v1/admin/bootstrap'
      path: '/api/v1/admin/bootstrap'
      fullPath: '/api/v1/admin/bootstrap'
      preLoaderRoute: typeof ApiV1AdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contractor/bootstrap': {
      id: '/api/v1/contractor/bootstrap'
      path: '/api/v1/contractor/bootstrap'
      fullPath: '/api/v1/contractor/bootstrap'
      preLoaderRoute: typeof ApiV1ContractorBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/public/stats': {
      id: '/api/v1/public/stats'
      path: '/api/v1/public/stats'
      fullPath: '/api/v1/public/stats'
      preLoaderRoute: typeof ApiV1PublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests/': {
      id: '/api/v1/requests/'
      path: '/api/v1/requests'
      fullPath: '/api/v1/requests/'
      preLoaderRoute: typeof ApiV1RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests/$id': {
      id: '/api/v1/requests/$id'
      path: '/api/v1/requests/$id'
      fullPath: '/api/v1/requests/$id'
      preLoaderRoute: typeof ApiV1RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/public/requests/$reference': {
      id: '/api/v1/public/requests/$reference'
      path: '/api/v1/public/requests/$reference'
      fullPath: '/api/v1/public/requests/$reference'
      preLoaderRoute: typeof ApiV1PublicRequestsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests/$id/assign': {
      id: '/api/v1/requests/$id/assign'
      path: '/assign'
      fullPath: '/api/v1/requests/$id/assign'
      preLoaderRoute: typeof ApiV1RequestsIdAssignRouteImport
      parentRoute: typeof ApiV1RequestsIdRoute
    }
    '/api/v1/requests/$id/notes': {
      id: '/api/v1/requests/$id/notes'
      path: '/notes'
      fullPath: '/api/v1/requests/$id/notes'
      preLoaderRoute: typeof ApiV1RequestsIdNotesRouteImport
      parentRoute: typeof ApiV1RequestsIdRoute
    }
    '/api/v1/requests/$id/photo-uploads': {
      id: '/api/v1/requests/$id/photo-uploads'
      path: '/photo-uploads'
      fullPath: '/api/v1/requests/$id/photo-uploads'
      preLoaderRoute: typeof ApiV1RequestsIdPhotoUploadsRouteImport
      parentRoute: typeof ApiV1RequestsIdRoute
    }
    '/api/v1/requests/$id/photos': {
      id: '/api/v1/requests/$id/photos'
      path: '/photos'
      fullPath: '/api/v1/requests/$id/photos'
      preLoaderRoute: typeof ApiV1RequestsIdPhotosRouteImport
      parentRoute: typeof ApiV1RequestsIdRoute
    }
    '/api/v1/requests/$id/transition': {
      id: '/api/v1/requests/$id/transition'
      path: '/transition'
      fullPath: '/api/v1/requests/$id/transition'
      preLoaderRoute: typeof ApiV1RequestsIdTransitionRouteImport
      parentRoute: typeof ApiV1RequestsIdRoute
    }
    '/api/v1/photos/$photoId/analysis/retry': {
      id: '/api/v1/photos/$photoId/analysis/retry'
      path: '/api/v1/photos/$photoId/analysis/retry'
      fullPath: '/api/v1/photos/$photoId/analysis/retry'
      preLoaderRoute: typeof ApiV1PhotosPhotoIdAnalysisRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests/$id/photo-uploads/$uploadId/complete': {
      id: '/api/v1/requests/$id/photo-uploads/$uploadId/complete'
      path: '/$uploadId/complete'
      fullPath: '/api/v1/requests/$id/photo-uploads/$uploadId/complete'
      preLoaderRoute: typeof ApiV1RequestsIdPhotoUploadsUploadIdCompleteRouteImport
      parentRoute: typeof ApiV1RequestsIdPhotoUploadsRoute
    }
  }
}

interface ApiV1RequestsIdPhotoUploadsRouteChildren {
  ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute: typeof ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute
}

const ApiV1RequestsIdPhotoUploadsRouteChildren: ApiV1RequestsIdPhotoUploadsRouteChildren =
  {
    ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute:
      ApiV1RequestsIdPhotoUploadsUploadIdCompleteRoute,
  }

const ApiV1RequestsIdPhotoUploadsRouteWithChildren =
  ApiV1RequestsIdPhotoUploadsRoute._addFileChildren(
    ApiV1RequestsIdPhotoUploadsRouteChildren,
  )

interface ApiV1RequestsIdRouteChildren {
  ApiV1RequestsIdAssignRoute: typeof ApiV1RequestsIdAssignRoute
  ApiV1RequestsIdNotesRoute: typeof ApiV1RequestsIdNotesRoute
  ApiV1RequestsIdPhotoUploadsRoute: typeof ApiV1RequestsIdPhotoUploadsRouteWithChildren
  ApiV1RequestsIdPhotosRoute: typeof ApiV1RequestsIdPhotosRoute
  ApiV1RequestsIdTransitionRoute: typeof ApiV1RequestsIdTransitionRoute
}

const ApiV1RequestsIdRouteChildren: ApiV1RequestsIdRouteChildren = {
  ApiV1RequestsIdAssignRoute: ApiV1RequestsIdAssignRoute,
  ApiV1RequestsIdNotesRoute: ApiV1RequestsIdNotesRoute,
  ApiV1RequestsIdPhotoUploadsRoute:
    ApiV1RequestsIdPhotoUploadsRouteWithChildren,
  ApiV1RequestsIdPhotosRoute: ApiV1RequestsIdPhotosRoute,
  ApiV1RequestsIdTransitionRoute: ApiV1RequestsIdTransitionRoute,
}

const ApiV1RequestsIdRouteWithChildren = ApiV1RequestsIdRoute._addFileChildren(
  ApiV1RequestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportRoute: ReportRoute,
  AdminAnalysesRoute: AdminAnalysesRoute,
  AdminContractorsRoute: AdminContractorsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ContractorHistoryRoute: ContractorHistoryRoute,
  ContractorLoginRoute: ContractorLoginRoute,
  TrackReferenceRoute: TrackReferenceRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContractorIndexRoute: ContractorIndexRoute,
  TrackIndexRoute: TrackIndexRoute,
  AdminRequestsIdRoute: AdminRequestsIdRoute,
  ApiInternalMaintenanceRoute: ApiInternalMaintenanceRoute,
  ApiV1ContractorsRoute: ApiV1ContractorsRoute,
  ContractorJobsIdRoute: ContractorJobsIdRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  ContractorJobsIndexRoute: ContractorJobsIndexRoute,
  ApiInternalMlProcessRoute: ApiInternalMlProcessRoute,
  ApiV1AdminAnalysesRoute: ApiV1AdminAnalysesRoute,
  ApiV1AdminBootstrapRoute: ApiV1AdminBootstrapRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1ContractorBootstrapRoute: ApiV1ContractorBootstrapRoute,
  ApiV1PublicStatsRoute: ApiV1PublicStatsRoute,
  ApiV1RequestsIdRoute: ApiV1RequestsIdRouteWithChildren,
  ApiV1RequestsIndexRoute: ApiV1RequestsIndexRoute,
  ApiV1PublicRequestsReferenceRoute: ApiV1PublicRequestsReferenceRoute,
  ApiV1PhotosPhotoIdAnalysisRetryRoute: ApiV1PhotosPhotoIdAnalysisRetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
