/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AdminContractorsRouteImport } from './routes/admin.contractors'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as ContractorHistoryRouteImport } from './routes/contractor.history'
import { Route as ContractorLoginRouteImport } from './routes/contractor.login'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TrackReferenceRouteImport } from './routes/track.$reference'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin.requests.index'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as ContractorJobsIndexRouteImport } from './routes/contractor.jobs.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractorsRoute = AdminContractorsRouteImport.update({
  id: '/admin/contractors',
  path: '/admin/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorHistoryRoute = ContractorHistoryRouteImport.update({
  id: '/contractor/history',
  path: '/contractor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorLoginRoute = ContractorLoginRouteImport.update({
  id: '/contractor/login',
  path: '/contractor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackReferenceRoute = TrackReferenceRouteImport.update({
  id: '/track/$reference',
  path: '/track/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/admin/requests/$id',
  path: '/admin/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorJobsIndexRoute = ContractorJobsIndexRouteImport.update({
  id: '/contractor/jobs/',
  path: '/contractor/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/track/': typeof TrackIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/contractor/jobs/': typeof ContractorJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/track': typeof TrackIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/contractor/jobs': typeof ContractorJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/contractors': typeof AdminContractorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/track/$reference': typeof TrackReferenceRoute
  '/track/': typeof TrackIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/contractor/jobs/': typeof ContractorJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report'
    | '/admin/contractors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reports'
    | '/contractor/history'
    | '/contractor/login'
    | '/track/$reference'
    | '/track/'
    | '/admin/requests/$id'
    | '/admin/requests/'
    | '/contractor/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report'
    | '/admin/contractors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reports'
    | '/contractor/history'
    | '/contractor/login'
    | '/track/$reference'
    | '/track'
    | '/admin/requests/$id'
    | '/admin/requests'
    | '/contractor/jobs'
  id:
    | '__root__'
    | '/'
    | '/report'
    | '/admin/contractors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reports'
    | '/contractor/history'
    | '/contractor/login'
    | '/track/$reference'
    | '/track/'
    | '/admin/requests/$id'
    | '/admin/requests/'
    | '/contractor/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportRoute: typeof ReportRoute
  AdminContractorsRoute: typeof AdminContractorsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  ContractorHistoryRoute: typeof ContractorHistoryRoute
  ContractorLoginRoute: typeof ContractorLoginRoute
  TrackReferenceRoute: typeof TrackReferenceRoute
  TrackIndexRoute: typeof TrackIndexRoute
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  ContractorJobsIndexRoute: typeof ContractorJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contractors': {
      id: '/admin/contractors'
      path: '/admin/contractors'
      fullPath: '/admin/contractors'
      preLoaderRoute: typeof AdminContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/history': {
      id: '/contractor/history'
      path: '/contractor/history'
      fullPath: '/contractor/history'
      preLoaderRoute: typeof ContractorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/login': {
      id: '/contractor/login'
      path: '/contractor/login'
      fullPath: '/contractor/login'
      preLoaderRoute: typeof ContractorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$reference': {
      id: '/track/$reference'
      path: '/track/$reference'
      fullPath: '/track/$reference'
      preLoaderRoute: typeof TrackReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/admin/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/jobs/': {
      id: '/contractor/jobs/'
      path: '/contractor/jobs'
      fullPath: '/contractor/jobs/'
      preLoaderRoute: typeof ContractorJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportRoute: ReportRoute,
  AdminContractorsRoute: AdminContractorsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  ContractorHistoryRoute: ContractorHistoryRoute,
  ContractorLoginRoute: ContractorLoginRoute,
  TrackReferenceRoute: TrackReferenceRoute,
  TrackIndexRoute: TrackIndexRoute,
  AdminRequestsIdRoute: AdminRequestsIdRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  ContractorJobsIndexRoute: ContractorJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
